# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Your PR has been merged @${{ github.event.pull_request.user.login }}!Claim your reward from https://aviyel.com'
            })
      - run: echo Claim your reward @${{ github.event.pull_request.user.login }}!
